question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "RAM stands for Random Access Memory.", "answer": "True"},
    {"text": "Linux was first created as an alternative to Windows XP.",
     "answer": "False"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "The logo for Snapchat is a Bell.", "answer": "False"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
             "you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, "
             "you are entitled to a state funeral.", "answer": "False"},
    {"text": "The programming language 'Python' is based off a modified version of 'JavaScript'.",
     "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "answer": "False"},
    {"text": "Ada Lovelace is often considered the first computer programmer.",
     "answer": "True"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
     "answer": "True"},
    {"text": "Time on Computers is measured via the EPOX System.",
     "answer": "False"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "The Windows ME operating system was released in the year 2000.",
     "answer": "True"},
    {"text": "The Python programming language gets its name from the British comedy group 'Monty Python'",
     "answer": "True"},
    {
        "text": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
        "answer": "False"},
    {"text": "Faust is a playable character in 'Guilty Gear Xrd Revelator'.", "answer": "True"},
    {"text": "Luigi is taller than Mario?", "answer": "True"},
    {"text": "Niko Bellic is the protagonist of Grand Theft Auto IV.", "answer": "True"},
    {"text": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series history.",
     "answer": "True"},
    {"text": "In Terraria, you can craft the Cell Phone pre-hardmode.", "answer": "True"},
    {"text": "In RuneScape, one must complete the 'Dragon Slayer' quest before equipping Rune Platelegs.",
     "answer": "False"},
    {"text": "Several characters in 'Super Mario 64' blink their eyes, including Mario himself.",
     "answer": "True"},
    {"text": "In the video game 'Splatoon', the playable characters were originally going to be rabbits instead of squids.",
     "answer": "True"},
    {"text": "The shotgun appears in every numbered Resident Evil game.", "answer": "True"},
    {"text": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
     "answer": "True"},
    {"text": "Leonardo DiCaprio won an Oscar for Best Actor in 'The Aviator'.",
     "answer": "False"},
    {"text": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
     "answer": "False"},
    {
        "text": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
        "answer": "True",
        "incorrect_answers": "False"},
    {"text": "The word 'Inception' came from the 2010 blockbuster hit 'Inception'.",
     "answer": "False"},
    {
        "text": "In the original script of 'The Matrix', the machines used humans as additional computing power instead of batteries.",
        "answer": "True"},
    {"text": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber "
             "during the filming of Star Wars.",
     "answer": "True"},
    {"text": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "answer": "True", },
    {"text": "'Minions' was released on the June 10th, 2015.",
     "answer": "False"},
    {"text": "The music group Daft Punk got their name from a negative review they recieved.",
     "answer": "True"},
    {"text": "Eurobeat is primarily an Italian genre of music.", "answer": "True"},
    {"text": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
     "answer": "False"},
    {"text": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
     "answer": "True"},
    {"text": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
     "answer": "True"},
    {"text": "A Saxophone is a brass instrument.", "answer": "False"},
    {"text": "Daft Punk originated in France.", "answer": "True"},
    {"text": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy "
             "with his contract with Warner Bros.", "answer": "True"},
    {"text": "John Williams composed the music for 'Star Wars'.", "answer": "True"},
    {"text": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
     "answer": "True"},
]
